#!/bin/sh /etc/rc.common
# shellcheck shell=sh

START=95
STOP=05
USE_PROCD=1

PROG=/usr/sbin/trafmon

validate_instance() {
	uci_validate_section trafmon instance "${1}" \
		'enabled:bool:0' \
		'ifname:string' \
		'led:string'
}

start_instance() {
	local cfg="$1"
	local enabled ifname led

	validate_instance "$cfg" || return 1
	config_get_bool enabled "$cfg" enabled 0
	[ "$enabled" -eq 1 ] || return 0

	config_get ifname "$cfg" ifname
	config_get led "$cfg" led "lan"

	[ -n "$ifname" ] || {
		logger -t trafmon "config '$cfg' missing ifname"
		return 1
	}

	procd_open_instance "trafmon.$cfg"
	procd_set_param command "$PROG" start "$ifname" "$led"
	# respawn: (sec_before, retries, retry_interval)
	procd_set_param respawn 300 3 5
	procd_close_instance
}

start_service() {
	config_load trafmon
	config_foreach start_instance instance
}
